doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            price_cents: App\Infrastructure\Mapping\Type\PriceCentsType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Infrastructure/Mapping'
                prefix: 'App\Domain\Model'
                alias: App
